import type { CanvasNode } from "@/components/canvas/workflow-canvas";
import type { Project } from "@/types/project";
import type { ProjectDetailCanvasDefinition } from "./types";

export function getBlueprint4AgentDetailCanvas(
  project: Project,
): ProjectDetailCanvasDefinition {
  const architectureOrigin = { x: 13, y: 70 };
  const architectureX = (x: number) => architectureOrigin.x + x;
  const architectureY = (y: number) => architectureOrigin.y + y;
  const featuresOrigin = { x: 101, y: 70 };
  const featuresX = (x: number) => featuresOrigin.x + x;
  const featuresY = (y: number) => featuresOrigin.y + y;
  const outcomeOrigin = { x: 93, y: 214 };
  const outcomeX = (x: number) => outcomeOrigin.x + x;
  const outcomeY = (y: number) => outcomeOrigin.y + y;

  const architectureNodes: CanvasNode[] = [
    {
      id: "architecture-title",
      kind: "note",
      appearance: "transparent",
      order: 6,
      x: architectureX(0),
      y: architectureY(0),
      width: 34,
      markdown: "# System Architecture",
    },
    {
      id: "application-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/application.svg", alt: "Application" },
      excludeFromSequence: true,
      x: architectureX(0),
      y: architectureY(5),
      width: 56,
      height: 660,
      markdown: "## Application",
    },
    {
      id: "frontend-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/frontend.svg", alt: "Frontend" },
      excludeFromSequence: true,
      x: architectureX(2),
      y: architectureY(14),
      width: 23,
      height: 260,
      markdown: "## Frontend",
    },
    {
      id: "frontend-description",
      kind: "note",
      appearance: "transparent",
      order: 9,
      x: architectureX(4),
      y: architectureY(34),
      width: 20,
      markdown:
        "**React와 TypeScript 기반의 풀스택 프론트엔드입니다.**\n\n**OpenAPI Generator**를 통해 백엔드 API 클라이언트를 자동 생성하여 프론트엔드와 백엔드가 동일한 API 명세를 공유하도록 구성했습니다. 또한 **Tauri 기반 Desktop 애플리케이션과** **Web** 환경을 함께 지원하며, 빌드된 정적 파일은 FastAPI 애플리케이션에서 함께 제공하여 단일 서버로 서비스를 운영할 수 있습니다.",
    },
    {
      id: "backend-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/backend.svg", alt: "Backend" },
      excludeFromSequence: true,
      x: architectureX(28),
      y: architectureY(14),
      width: 27,
      height: 500,
      markdown: "## Backend",
    },
    {
      id: "react",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/react.svg", alt: "React" },
      order: 7,
      x: architectureX(4),
      y: architectureY(23),
      width: 9.5,
      markdown: "**React**",
    },
    {
      id: "typescript",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/typescript.svg", alt: "TypeScript" },
      order: 8,
      x: architectureX(14),
      y: architectureY(23),
      width: 9.5,
      markdown: "**TypeScript**",
    },
    {
      id: "fastapi",
      kind: "note",
      icon: { src: "/icons/tech/fastapi.svg", alt: "FastAPI" },
      layer: "background",
      order: 10,
      x: architectureX(29.5),
      y: architectureY(22),
      width: 24,
      height: 230,
      markdown: "**FastAPI**\n\nApplication API",
    },
    {
      id: "sqlalchemy",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/sqlalchemy.svg", alt: "SQLAlchemy" },
      order: 11,
      x: architectureX(35),
      y: architectureY(31),
      width: 11,
      markdown: "**SQLAlchemy**\n\nData Access / ORM",
    },
    {
      id: "database",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/database.svg", alt: "Database" },
      order: 12,
      x: architectureX(30),
      y: architectureY(43),
      width: 11,
      markdown: "**Database**",
    },
    {
      id: "redis",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/redis.svg", alt: "Redis" },
      order: 13,
      x: architectureX(42),
      y: architectureY(43),
      width: 11,
      markdown: "**Redis**",
    },
    {
      id: "backend-description",
      kind: "note",
      appearance: "transparent",
      order: 14,
      x: architectureX(57),
      y: architectureY(20),
      width: 25,
      markdown:
        "**AI 애플리케이션 개발에 필요한 기반 기능을 표준화한 FastAPI 기반 백엔드입니다.**\n\n**인증(Authentication), OAuth, 사용자 설정, API Key, 데이터 접근 계층** 등 대부분의 서비스에서 반복적으로 구현되는 기능을 기본 제공합니다. **SQLAlchemy** 기반으로 데이터베이스를 추상화하고 **Redis**를 활용한 캐시 및 세션 관리까지 포함하여, 프로젝트 초기 설정 없이 바로 기능 개발을 시작할 수 있도록 설계했습니다.",
    },
    {
      id: "deploy-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/deploy.svg", alt: "Deploy" },
      excludeFromSequence: true,
      x: architectureX(0),
      y: architectureY(58),
      width: 40,
      height: 600,
      markdown: "## Deploy",
    },
    {
      id: "deploy-description",
      kind: "note",
      appearance: "transparent",
      order: 21,
      x: architectureX(8),
      y: architectureY(103),
      width: 22,
      markdown:
        "**개발 환경과 운영 환경이 동일한 빌드 흐름을 사용하도록 배포 파이프라인을 구성했습니다**.\n\n **Hatch**를 공통 빌드 엔트리로 사용하여 로컬 개발 환경과 **GitHub Actions** 기반 CI/CD가 동일한 빌드 과정을 공유합니다. 생성된 결과물은 **Docker Image, GitHub Container Registry(GHCR), Tauri Desktop Application**으로 자동 배포되어 일관된 릴리스 환경을 제공합니다.",
    },
    {
      id: "hatch-script",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/hatch.svg", alt: "Hatch" },
      order: 15,
      x: architectureX(14),
      y: architectureY(66),
      width: 12,
      markdown: "**Hatch Script**",
    },
    {
      id: "local-docker",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/docker.svg", alt: "Docker" },
      order: 16,
      x: architectureX(5),
      y: architectureY(78),
      width: 10,
      markdown: "**Local Build**",
    },
    {
      id: "github-actions",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/github-actions.svg", alt: "GitHub Actions" },
      order: 17,
      x: architectureX(24),
      y: architectureY(78),
      width: 11,
      markdown: "**GitHub Actions**",
    },
    {
      id: "docker-image",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/docker.svg", alt: "Docker Image" },
      order: 18,
      x: architectureX(4),
      y: architectureY(91),
      width: 9,
      markdown: "**Docker Image**",
    },
    {
      id: "ghcr",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/github.svg", alt: "GHCR" },
      order: 19,
      x: architectureX(16),
      y: architectureY(91),
      width: 9,
      markdown: "**GHCR**",
    },
    {
      id: "tauri",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/tauri.svg", alt: "Tauri" },
      order: 20,
      x: architectureX(29),
      y: architectureY(91),
      width: 9,
      markdown: "**Tauri App**",
    },
    {
      id: "observability-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/observability.svg", alt: "Observability" },
      excludeFromSequence: true,
      x: architectureX(42),
      y: architectureY(58),
      width: 28,
      height: 550,
      markdown: "## Observability",
    },
    {
      id: "observability-description",
      kind: "note",
      appearance: "transparent",
      order: 25,
      x: architectureX(43),
      y: architectureY(99),
      width: 25,
      markdown:
        "**운영 환경을 지속적으로 관찰하고 분석할 수 있는 모니터링 환경을 기본 제공합니다.**\n\n**OpenTelemetry**를 통해 **Metrics와 Trace**를 수집하고, **Prometheus와 Grafana**를 활용하여 애플리케이션 상태를 시각화합니다. 개발 단계부터 운영 환경까지 동일한 Observability 구성을 제공하여 서비스 상태를 지속적으로 모니터링할 수 있도록 설계했습니다.",
    },
    {
      id: "opentelemetry",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/opentelemetry.svg", alt: "OpenTelemetry" },
      order: 22,
      x: architectureX(50),
      y: architectureY(70),
      width: 12,
      markdown: "**OpenTelemetry**",
    },
    {
      id: "prometheus",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/prometheus.svg", alt: "Prometheus" },
      order: 23,
      x: architectureX(46),
      y: architectureY(84),
      width: 10,
      markdown: "**Prometheus**",
    },
    {
      id: "grafana",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/grafana.svg", alt: "Grafana" },
      order: 24,
      x: architectureX(58),
      y: architectureY(84),
      width: 10,
      markdown: "**Grafana**",
    },
  ];

  const nodes: CanvasNode[] = [
    {
      id: "project-icon",
      kind: "note",
      appearance: "transparent",
      excludeFromSequence: true,
      x: 13,
      y: 7,
      width: 11,
      image: {
        src: "/b4a.svg",
        alt: "Blueprint4Agent icon",
        width: 120,
        height: 120,
        frame: "plain",
      },
      markdown: "",
    },
    {
      id: "overview",
      kind: "note",
      appearance: "transparent",
      order: 1,
      x: 26,
      y: 8,
      width: 52,
      markdown:
        "# Blueprint4Agent\n\n**Blueprint4Agent는 에이전틱 코딩 기반으로 AI 애플리케이션을 빠르게 시작하고 운영하기 위한 프로젝트 블루프린트입니다.**\n\nFastAPI 기반 풀스택 서버 템플릿인 **B4FastAPI**를 중심으로 인증, 배포, 문서화, 테스트, CI/CD, 모니터링까지 프로젝트에 필요한 기반 환경을 하나의 표준 구조로 제공합니다. 따라서 반복적으로 필요한 초기 설정을 미리 갖춘 상태에서 개발자가 **AI Agent를 활용해 기능 구현에 집중할 수 있는 개발 환경**을 목표로 설계했습니다.\n\n이 페이지에서는 BluePrint4Agent를 개발하게 된 목표와 시스템 아키텍처, 주요 기능 및 구현 과정, 그리고 프로젝트를 통해 얻은 결과와 경험을 소개합니다.",
    },
    {
      id: "info",
      title: "Info",
      kind: "note",
      order: 2,
      x: 82,
      y: 10,
      width: 25,
      markdown: [
        "- :calendar: 2026.2 ~ In Progress",
        "- :stack: `FastAPI` `React` `TypeScript` `Docker` `Tauri` `OpenTelemetry`",
        "",
        `- :github: [GitHub|Blueprint4Agent GitHub 조직으로 이동](${project.href})`,
        "- :package: [GHCR|B4FastAPI GHCR 패키지로 이동](https://github.com/orgs/Blueprint4Agent/packages/container/package/b4fastapi)",
        "- :website: [Docs|Blueprint4Agent 문서 사이트로 이동](https://blueprint4agent.github.io/)",
      ].join("\n"),
    },
    {
      id: "project-goals",
      kind: "note",
      appearance: "transparent",
      order: 3,
      x: 13,
      y: 37,
      width: 48,
      markdown:
        "# Project Goals\n\n**AI Agent가 코드를 잘 작성하려면 프로젝트의 기반 구조가 먼저 준비되어 있어야 합니다.**\n\n에이전틱 코딩을 반복적으로 적용할수록 인증, 배포, 테스트, 문서화, API 타입 생성, 모니터링 환경과 같은 기반 작업을 프로젝트마다 다시 구성해야 하는 문제가 발생합니다.\n\nBlueprint4Agent는 이러한 반복 작업을 줄이고, 프로젝트를 시작하는 순간부터 개발과 운영이 가능한 환경을 제공하기 위해 시작했습니다. AI Agent와 개발자가 동일한 개발 규칙 안에서 협업하고, 기능 구현에만 집중할 수 있는 표준 프로젝트 구조를 만드는 것을 목표로 합니다.",
    },
    {
      id: "goals-list",
      title: "Goals",
      kind: "note",
      order: 4,
      x: 66,
      y: 42,
      width: 33,
      markdown: [
        "",
        "- FastAPI 기반 풀스택 프로젝트 템플릿 제공",
        "- 인증·배포·문서화 등 공통 개발 환경 표준화",
        "- OpenAPI 기반 타입 안전한 API 연동",
        "- GitHub Actions 기반 CI/CD 자동화",
        "- AI Agent가 이해하기 쉬운 프로젝트 구조 제공",
      ].join("\n"),
    },
    {
      id: "quick-start",
      title: "Quick Start",
      kind: "note",
      order: 5,
      x: 111,
      y: 15,
      width: 72,
      markdown:
        "## 실행 방법\n\n### 1. 저장소 복제\n\n```bash\ngit clone https://github.com/Blueprint4Agent/b4fastapi.git\ncd b4fastapi\n```\n\n### 2. 백엔드 서버 실행\n\n```bash\ncd src/backend\nuv sync\nuv run uvicorn b4fastapi.server:app --reload\n```\n\n### 3. 프론트엔드 실행\n\n```bash\ncd src/frontend\nnpm install\nnpm run dev\n```\n\n### 4. Tauri 데스크톱 실행\n\n```bash\ncd src/frontend\nnpm run tauri dev\n```\n\n**Backend Server**, **Frontend Dev Server**, **Tauri Desktop App**을 각각 실행해 웹과 데스크톱 환경을 함께 확인할 수 있습니다.",
    },
    ...architectureNodes,
    {
      id: "features-title",
      kind: "note",
      appearance: "transparent",
      order: 26,
      x: featuresX(0),
      y: featuresY(0),
      width: 30,
      markdown: "# Features",
    },
    {
      id: "feature-login-light-image",
      kind: "note",
      appearance: "transparent",
      order: 27,
      x: featuresX(0),
      y: featuresY(5),
      width: 40,
      image: {
        src: "/images/b4a-features/login-light.png",
        alt: "B4A login light screen",
        width: 2446,
        height: 1632,
        frame: "outline",
        frameHeight: 400,
        fit: "contain",
      },
      markdown: "",
    },
    {
      id: "feature-foundation",
      kind: "note",
      appearance: "feature",
      order: 28,
      x: featuresX(0),
      y: featuresY(36),
      width: 40,
      markdown:
        "## Authentication & Service Foundation\n\n**Authentication, OAuth, Refresh Token, 사용자 설정, API Key** 등 대부분의 서비스에서 반복적으로 구현되는 기반 기능을 기본 제공합니다.",
    },
    {
      id: "feature-showcase-image",
      kind: "note",
      appearance: "transparent",
      order: 29,
      x: featuresX(42),
      y: featuresY(5),
      width: 40,
      image: {
        src: "/images/b4a-features/showcase.png",
        alt: "B4A showcase page",
        width: 2448,
        height: 1618,
        frame: "outline",
        frameHeight: 400,
        fit: "contain",
      },
      markdown: "",
    },
    {
      id: "feature-showcase",
      kind: "note",
      appearance: "feature",
      order: 30,
      x: featuresX(42),
      y: featuresY(36),
      width: 40,
      markdown:
        "## Showcase\n\n프로젝트에서 사용할 수 있는 **UI 컴포넌트와 화면 예시**를 미리 제공합니다. 개발자는 원하는 UI를 직접 확인하고, AI Agent는 Showcase를 참고하여 자연어 지시만으로 화면을 생성하거나 기존 레이아웃을 수정하는 등 일관된 UI 구성을 수행할 수 있습니다.",
    },
    {
      id: "feature-login-dark-image",
      kind: "note",
      appearance: "transparent",
      order: 31,
      x: featuresX(0),
      y: featuresY(48),
      width: 40,
      image: {
        src: "/images/b4a-features/login-dark.png",
        alt: "B4A login dark desktop screen",
        width: 2564,
        height: 1632,
        frame: "outline",
        frameHeight: 400,
        fit: "contain",
      },
      markdown: "",
    },
    {
      id: "feature-desktop",
      kind: "note",
      appearance: "feature",
      order: 32,
      x: featuresX(0),
      y: featuresY(79),
      width: 40,
      markdown:
        "## Desktop Application Support\n\n**Tauri 기반 데스크톱 애플리케이션 구조**를 함께 제공하여 하나의 코드베이스에서 Web과 Desktop 환경을 모두 지원할 수 있습니다.",
    },
    {
      id: "feature-ghcr-image",
      kind: "note",
      appearance: "transparent",
      order: 33,
      x: featuresX(42),
      y: featuresY(48),
      width: 40,
      image: {
        src: "/images/b4a-features/ghcr.png",
        alt: "B4A GHCR package page",
        width: 1868,
        height: 1434,
        frame: "outline",
        frameHeight: 400,
        fit: "contain",
      },
      markdown: "",
    },
    {
      id: "feature-deploy",
      kind: "note",
      appearance: "feature",
      order: 34,
      x: featuresX(42),
      y: featuresY(79),
      width: 40,
      markdown:
        "## Deployment & CI Workflow\n\n**Docker 기반 개발 환경**과 **GitHub Actions 기반 CI/CD**를 제공하며, Docker Image 생성, GitHub Container Registry(GHCR) 배포, Desktop Build Workflow까지 일관된 배포 환경을 제공합니다.",
    },
    {
      id: "feature-grafana-image",
      kind: "note",
      appearance: "transparent",
      order: 35,
      x: featuresX(0),
      y: featuresY(91),
      width: 40,
      image: {
        src: "/images/b4a-features/grafana.png",
        alt: "B4A Grafana dashboard",
        width: 2400,
        height: 1194,
        frame: "outline",
        frameHeight: 398,
        fit: "contain",
      },
      markdown: "",
    },
    {
      id: "feature-observability",
      kind: "note",
      appearance: "feature",
      order: 36,
      x: featuresX(0),
      y: featuresY(122),
      width: 40,
      markdown:
        "## Observability\n\n**Prometheus 기반 Metrics**와 **OpenTelemetry 기반 Metrics, Traces, Logs**를 지원하여 애플리케이션의 상태를 모니터링하고 운영 환경을 관찰할 수 있는 기반을 제공합니다.",
    },
    {
      id: "results",
      kind: "note",
      appearance: "transparent",
      order: 37,
      x: outcomeX(0),
      y: outcomeY(0),
      width: 42,
      markdown:
        "# Results\n\n**반복되는 프로젝트 준비 과정을 하나의 개발 환경으로 정리했습니다.**\n\nBlueprint4Agent는 AI 애플리케이션을 시작할 때 반복적으로 구현하던 인증, API 구조, OpenAPI 기반 타입 생성, Docker 배포, CI/CD, 문서화, 모니터링 환경을 하나의 템플릿으로 통합한 프로젝트입니다.\n\n저는 프로젝트를 생성하는 순간부터 개발과 운영이 가능한 환경을 만드는 것을 목표로 했습니다. 이를 통해 반복적인 초기 설정을 줄이고, AI Agent와 개발자가 프로젝트 구성보다 기능 구현에 집중할 수 있는 개발 흐름을 만들었습니다.",
    },
    {
      id: "lessons",
      kind: "note",
      appearance: "transparent",
      order: 38,
      x: outcomeX(50),
      y: outcomeY(0),
      width: 42,
      markdown:
        "# Lessons Learned\n\n**AI가 잘 개발하려면 프로젝트도 AI 친화적으로 설계되어야 했습니다.**\n\nBlueprint4Agent를 개발하면서 FastAPI 기반 풀스택 아키텍처, Docker와 GitHub Actions를 활용한 배포 파이프라인, OpenAPI 기반 타입 생성, Tauri 기반 Desktop 지원, Prometheus와 OpenTelemetry를 활용한 Observability 환경까지 하나의 개발 흐름으로 정리할 수 있었습니다.\n\n무엇보다 AI의 생산성을 높이는 핵심은 새로운 기능을 계속 추가하는 것이 아니라, AI가 이해하기 쉬운 프로젝트 구조와 일관된 개발 규칙을 먼저 제공하는 것이라는 점을 경험했습니다. 이러한 경험은 앞으로 새로운 AI 애플리케이션을 시작할 때도 동일한 개발 환경과 운영 방식을 적용할 수 있는 기반이 되었습니다.",
    },
  ];

  return {
    nodes,
    edges: [
      {
        id: "frontend-to-backend",
        from: { nodeId: "frontend-section", side: "right" },
        to: { nodeId: "backend-section", side: "left" },
        bidirectional: true,
      },
      {
        id: "sqlalchemy-to-database",
        from: { nodeId: "sqlalchemy", side: "bottom" },
        to: { nodeId: "database", side: "top" },
        bidirectional: true,
      },
      {
        id: "fastapi-to-redis",
        from: { nodeId: "fastapi", side: "bottom" },
        to: { nodeId: "redis", side: "top" },
        bidirectional: true,
      },
      {
        id: "application-to-deploy",
        from: { nodeId: "application-section", side: "bottom" },
        to: { nodeId: "deploy-section", side: "top" },
        directed: true,
      },
      {
        id: "application-to-observability",
        from: { nodeId: "backend-section", side: "bottom" },
        to: { nodeId: "observability-section", side: "top" },
        directed: true,
      },
      {
        id: "hatch-to-local",
        from: { nodeId: "hatch-script", side: "bottom" },
        to: { nodeId: "local-docker", side: "top" },
        directed: true,
      },
      {
        id: "hatch-to-github-actions",
        from: { nodeId: "hatch-script", side: "bottom" },
        to: { nodeId: "github-actions", side: "top" },
        directed: true,
      },
      {
        id: "local-to-docker-image",
        from: { nodeId: "local-docker", side: "bottom" },
        to: { nodeId: "docker-image", side: "top" },
        directed: true,
      },
      {
        id: "github-actions-to-ghcr",
        from: { nodeId: "github-actions", side: "bottom" },
        to: { nodeId: "ghcr", side: "top" },
        directed: true,
      },
      {
        id: "github-actions-to-tauri",
        from: { nodeId: "github-actions", side: "bottom" },
        to: { nodeId: "tauri", side: "top" },
        directed: true,
      },
      {
        id: "otel-to-prometheus",
        from: { nodeId: "opentelemetry", side: "bottom" },
        to: { nodeId: "prometheus", side: "top" },
        directed: true,
      },
      {
        id: "prometheus-to-grafana",
        from: { nodeId: "prometheus", side: "right" },
        to: { nodeId: "grafana", side: "left" },
        directed: true,
      },
    ],
  };
}
