import type { CanvasEdge, CanvasNode } from "@/components/canvas/workflow-canvas";
import type { Project } from "@/types/project";
import type { ProjectDetailCanvasDefinition } from "./types";

export function getBlueprint4AgentDetailCanvas(project: Project): ProjectDetailCanvasDefinition {
  const architectureOrigin = { x: 13, y: 58 };
  const architectureX = (x: number) => architectureOrigin.x + x;
  const architectureY = (y: number) => architectureOrigin.y + y;
  const featuresOrigin = { x: 88, y: 58 };
  const featuresX = (x: number) => featuresOrigin.x + x;
  const featuresY = (y: number) => featuresOrigin.y + y;
  const outcomeOrigin = { x: 13, y: 146 };
  const outcomeX = (x: number) => outcomeOrigin.x + x;
  const outcomeY = (y: number) => outcomeOrigin.y + y;

  const nodes: CanvasNode[] = [
    {
      id: "project-icon",
      kind: "note",
      appearance: "transparent",
      excludeFromSequence: true,
      x: 13,
      y: 7,
      width: 11,
      image: {
        src: "/b4a.svg",
        alt: "Blueprint4Agent icon",
        width: 120,
        height: 120,
        frame: "plain",
      },
      markdown: "",
    },
    {
      id: "summary",
      kind: "note",
      appearance: "transparent",
      order: 1,
      x: 26,
      y: 8,
      width: 50,
      markdown:
        "**Blueprint4Agent는 에이전틱 코딩 기반으로 애플리케이션을 빠르게 시작하고 운영하기 위한 프로젝트 블루프린트입니다.**\n\nFastAPI 기반 풀스택 서버 템플릿인 **B4FastAPI**와 GitHub 저장소 관리 자동화를 위한 **B4Bot**을 통해 인증, 배포, 문서화, 테스트, CI, 저장소 운영 흐름을 표준화했습니다.\n\n반복적으로 필요한 기반 구조를 미리 갖춘 상태에서 **AI Agent와 개발자가 기능 구현에 집중할 수 있는 환경**을 목표로 구성했습니다.",
    },
    {
      id: "info",
      title: "Info",
      kind: "note",
      order: 2,
      x: 79,
      y: 10,
      width: 24,
      markdown: [
        "- :calendar: 2026.2 ~ In Progress",
        "- :stack: `FastAPI` `React` `TypeScript` `Docker` `GitHub Actions`",
        "",
        `- :github: [GitHub|Blueprint4Agent GitHub 조직으로 이동](${project.href})`,
        "- :website: [Docs|Blueprint4Agent 문서 사이트로 이동](https://blueprint4agent.github.io/)",
      ].join("\n"),
    },
    {
      id: "project-goals",
      kind: "note",
      appearance: "transparent",
      order: 3,
      x: 13,
      y: 34,
      width: 47,
      markdown:
        "# Project Goals\n\n**AI Agent가 코드를 잘 작성하려면 프로젝트의 기반 구조가 먼저 안정적이어야 합니다.**\n\n에이전틱 코딩을 반복적으로 활용하다 보면 인증, 배포, 테스트, 문서화, API 타입 생성, 저장소 규칙 같은 기반 작업을 매번 다시 구성해야 하는 문제가 생깁니다.\n\nBlueprint4Agent는 이런 반복 작업을 줄이기 위해 시작한 프로젝트입니다. FastAPI 기반 서버 템플릿과 GitHub 자동화 도구를 통해 프로젝트 시작 단계부터 운영 가능한 구조를 제공하고, AI Agent가 일관된 규칙 안에서 작업할 수 있는 환경을 목표로 합니다.",
    },
    {
      id: "goals-list",
      title: "Goals",
      kind: "note",
      order: 4,
      x: 64,
      y: 41,
      width: 30,
      markdown: [
        "",
        "- FastAPI 풀스택 템플릿 제공",
        "- 인증·배포·문서화 표준화",
        "- OpenAPI 기반 타입 흐름 구성",
        "- GitHub Actions 기반 운영 자동화",
        "- Agent가 작업하기 쉬운 저장소 규칙 제공",
      ].join("\n"),
    },
    {
      id: "quick-start",
      title: "Quick Start",
      kind: "note",
      order: 5,
      x: 100,
      y: 17,
      width: 40,
      markdown:
        "## B4FastAPI\n\n```bash\nmake init\nmake backend-install\nmake backend-dev\nmake frontend-install\nmake frontend-dev\n```\n\n## B4Bot\n\n```bash\nnpm install\nnpm run typecheck\nnpm run build\n```\n\n```yaml\n- uses: Blueprint4Agent/B4Bot@v1\n  with:\n    config-path: \".github/b4bot.yml\"\n```",
    },
    {
      id: "architecture-title",
      kind: "note",
      appearance: "transparent",
      order: 6,
      x: architectureX(0),
      y: architectureY(0),
      width: 34,
      markdown: "# System Architecture",
    },
    {
      id: "application-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/application.svg", alt: "Application" },
      excludeFromSequence: true,
      x: architectureX(0),
      y: architectureY(5),
      width: 60,
      height: 480,
      markdown: "## Application",
    },
    {
      id: "backend-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/backend.svg", alt: "Backend" },
      excludeFromSequence: true,
      x: architectureX(3),
      y: architectureY(14),
      width: 25,
      height: 230,
      markdown: "## Backend",
    },
    {
      id: "frontend-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/frontend.svg", alt: "Frontend" },
      excludeFromSequence: true,
      x: architectureX(32),
      y: architectureY(14),
      width: 25,
      height: 230,
      markdown: "## Frontend",
    },
    {
      id: "fastapi",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/fastapi.svg", alt: "FastAPI" },
      order: 7,
      x: architectureX(5),
      y: architectureY(25),
      width: 10,
      markdown: "**FastAPI**",
    },
    {
      id: "sqlalchemy",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/sqlalchemy.svg", alt: "SQLAlchemy" },
      order: 8,
      x: architectureX(16),
      y: architectureY(25),
      width: 10,
      markdown: "**SQLAlchemy**",
    },
    {
      id: "react",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/react.svg", alt: "React" },
      order: 9,
      x: architectureX(34),
      y: architectureY(25),
      width: 10,
      markdown: "**React**",
    },
    {
      id: "typescript",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/typescript.svg", alt: "TypeScript" },
      order: 10,
      x: architectureX(45),
      y: architectureY(25),
      width: 10,
      markdown: "**TypeScript**",
    },
    {
      id: "automation-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/tech/github-actions.svg", alt: "Automation" },
      excludeFromSequence: true,
      x: architectureX(0),
      y: architectureY(43),
      width: 60,
      height: 240,
      markdown: "## Automation & Deploy",
    },
    {
      id: "github-actions",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/github-actions.svg", alt: "GitHub Actions" },
      order: 11,
      x: architectureX(5),
      y: architectureY(54),
      width: 13,
      markdown: "**GitHub Actions**",
    },
    {
      id: "docker",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/docker.svg", alt: "Docker" },
      order: 12,
      x: architectureX(20),
      y: architectureY(54),
      width: 10,
      markdown: "**Docker**",
    },
    {
      id: "b4bot",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/github.svg", alt: "B4Bot" },
      order: 13,
      x: architectureX(33),
      y: architectureY(54),
      width: 10,
      markdown: "**B4Bot**",
    },
    {
      id: "docusaurus",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/docusaurus.svg", alt: "Docusaurus" },
      order: 14,
      x: architectureX(45),
      y: architectureY(54),
      width: 12,
      markdown: "**Docs**",
    },
    {
      id: "features-title",
      kind: "note",
      appearance: "transparent",
      order: 15,
      x: featuresX(0),
      y: featuresY(0),
      width: 30,
      markdown: "# Features",
    },
    ...[
      ["feature-blueprint", "Full-stack FastAPI Blueprint", "FastAPI, SQLAlchemy, Alembic, Redis 기반 백엔드와 React, TypeScript, OpenAPI 타입 생성 기반 프론트엔드를 포함한 **풀스택 템플릿**입니다."],
      ["feature-foundation", "Auth / Settings Foundation", "로그인, OAuth, refresh token, profile, settings, API key 같은 **반복적인 서비스 기반 기능**을 미리 포함합니다."],
      ["feature-deploy", "Docker / CI Workflow", "Docker 기반 로컬 배포, GHCR 이미지 배포, GitHub Actions build pipeline, desktop build workflow를 제공합니다."],
      ["feature-agent", "Agentic Repository Automation", "B4Bot을 통해 저장소를 주기적으로 점검하고 feature, error, refactor, secure 범위의 관리 이슈를 생성합니다."],
    ].map(([id, title, body], index) => ({
      id,
      kind: "note" as const,
      appearance: "feature" as const,
      order: 16 + index,
      x: featuresX(index % 2 === 0 ? 0 : 42),
      y: featuresY(10 + Math.floor(index / 2) * 22),
      width: 38,
      markdown: `## ${title}\n\n${body}`,
    })),
    {
      id: "results",
      kind: "note",
      appearance: "transparent",
      order: 20,
      x: outcomeX(0),
      y: outcomeY(0),
      width: 40,
      markdown:
        "# Results\n\n**반복적인 초기 설정 없이 바로 기능 개발을 시작할 수 있는 기반을 만들었습니다.**\n\nB4FastAPI를 통해 인증, API 구조, 프론트엔드 타입 생성, Docker 배포, CI, 문서화 규칙을 하나의 템플릿으로 정리했고, B4Bot을 통해 저장소 운영 이슈를 자동으로 생성하는 Agent 기반 관리 흐름을 구성했습니다.\n\n결과적으로 에이전틱 코딩을 위한 프로젝트 시작점과 저장소 운영 자동화 기반을 함께 갖춘 구조가 되었습니다.",
    },
    {
      id: "lessons",
      kind: "note",
      appearance: "transparent",
      order: 21,
      x: outcomeX(44),
      y: outcomeY(4),
      width: 40,
      markdown:
        "# Lessons Learned\n\n**에이전틱 코딩에서 중요한 것은 AI가 안정적으로 작업할 수 있는 프로젝트 구조와 규칙을 먼저 제공하는 것이었습니다.**\n\n이 프로젝트를 통해 FastAPI 기반 풀스택 템플릿, Docker/GitHub Actions 배포 흐름, OpenAPI 기반 프론트엔드 타입 생성, Docusaurus 문서화 구조, GitHub Action 기반 Agent 자동화 구성을 정리할 수 있었습니다.",
    },
  ];

  return {
    nodes,
    edges: [
      {
        id: "backend-to-frontend",
        from: { nodeId: "backend-section", side: "right" },
        to: { nodeId: "frontend-section", side: "left" },
        bidirectional: true,
      },
      {
        id: "application-to-automation",
        from: { nodeId: "application-section", side: "bottom" },
        to: { nodeId: "automation-section", side: "top" },
        directed: true,
      },
      {
        id: "b4bot-to-actions",
        from: { nodeId: "b4bot", side: "left" },
        to: { nodeId: "github-actions", side: "right" },
        bidirectional: true,
      },
    ],
  };
}
