import type { CanvasEdge, CanvasNode } from "@/components/canvas/workflow-canvas";
import type { Project } from "@/types/project";
import type { ProjectDetailCanvasDefinition } from "./types";

const hippoboxArchitectureEdges: CanvasEdge[] = [
  {
    id: "frontend-to-fastapi",
    from: { nodeId: "frontend-section", side: "right" },
    to: { nodeId: "fastapi", side: "left" },
    bidirectional: true,
  },
  {
    id: "fastapi-to-qdrant",
    from: { nodeId: "fastapi", side: "bottom" },
    to: { nodeId: "qdrant", side: "top" },
    bidirectional: true,
  },
  {
    id: "sqlalchemy-to-database",
    from: { nodeId: "sqlalchemy", side: "bottom" },
    to: { nodeId: "database", side: "top" },
    bidirectional: true,
  },
  {
    id: "mcp-clients-to-mcp",
    from: { nodeId: "mcp-clients-section", side: "left" },
    to: { nodeId: "mcp", side: "right" },
    bidirectional: true,
  },
  {
    id: "application-to-deploy",
    from: { nodeId: "application-section", side: "bottom" },
    to: { nodeId: "deploy-section", side: "top" },
    directed: true,
  },
  {
    id: "hatch-to-local",
    from: { nodeId: "hatch-script", side: "bottom" },
    to: { nodeId: "local-build", side: "top" },
    directed: true,
  },
  {
    id: "hatch-to-github-actions",
    from: { nodeId: "hatch-script", side: "bottom" },
    to: { nodeId: "github-actions", side: "top" },
    directed: true,
  },
  {
    id: "local-to-docker-image",
    from: { nodeId: "local-build", side: "bottom" },
    to: { nodeId: "docker-image", side: "top" },
    directed: true,
  },
  {
    id: "github-actions-to-pypi",
    from: { nodeId: "github-actions", side: "bottom" },
    to: { nodeId: "pypi", side: "top" },
    directed: true,
  },
  {
    id: "github-actions-to-ghcr",
    from: { nodeId: "github-actions", side: "bottom" },
    to: { nodeId: "ghcr", side: "top" },
    directed: true,
  },
];

export function getHippoBoxDetailCanvas(
  project: Project,
): ProjectDetailCanvasDefinition {
  const architectureOrigin = { x: 13, y: 70 };
  const architectureX = (x: number) => architectureOrigin.x + x;
  const architectureY = (y: number) => architectureOrigin.y + y;
  const featuresOrigin = { x: 101, y: 70 };
  const featuresX = (x: number) => featuresOrigin.x + x;
  const featuresY = (y: number) => featuresOrigin.y + y;
  const outcomeOrigin = { x: 93, y: 171 };
  const outcomeX = (x: number) => outcomeOrigin.x + x;
  const outcomeY = (y: number) => outcomeOrigin.y + y;

  // Default system architecture layout pattern for project detail pages.
  // Future project architecture canvases should follow this structure:
  // overview slogan -> sectioned architecture groups -> nearby transparent
  // explanation slogans -> deploy pipeline.
  const architectureNodes: CanvasNode[] = [
    {
      id: "architecture-title",
      kind: "note",
      appearance: "transparent",
      order: 6,
      x: architectureX(0),
      y: architectureY(0),
      width: 30,
      markdown: "# System Architecture",
    },
    {
      id: "application-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/application.svg", alt: "Application" },
      excludeFromSequence: true,
      x: architectureX(0),
      y: architectureY(5),
      width: 56,
      height: 660,
      markdown: "## Application",
    },
    {
      id: "frontend-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/frontend.svg", alt: "Frontend" },
      excludeFromSequence: true,
      x: architectureX(2),
      y: architectureY(14),
      width: 23,
      height: 260,
      markdown: "## Frontend",
    },
    {
      id: "react",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/react.svg", alt: "React" },
      order: 7,
      x: architectureX(4),
      y: architectureY(23),
      width: 9.5,
      markdown: "**React**",
    },
    {
      id: "typescript",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/typescript.svg", alt: "TypeScript" },
      order: 8,
      x: architectureX(14),
      y: architectureY(23),
      width: 9.5,
      markdown: "**TypeScript**",
    },
    {
      id: "frontend-description",
      kind: "note",
      appearance: "transparent",
      order: 9,
      x: architectureX(4),
      y: architectureY(36),
      width: 20,
      markdown:
        "**React와 TypeScript 기반의 모놀리식 프론트엔드입니다.**\n\n**OpenAPI Generator**를 통해 백엔드 API 클라이언트를 자동 생성하여 **프론트엔드와 백엔드 간 인터페이스**를 일관되게 유지했습니다. 배포 시에는 **정적 파일을 모놀리식 애플리케이션에서 함께 제공**하여 단일 서버만으로 서비스를 운영할 수 있도록 구성했습니다.",
    },
    {
      id: "backend-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/backend.svg", alt: "Backend" },
      excludeFromSequence: true,
      x: architectureX(28),
      y: architectureY(14),
      width: 27,
      height: 500,
      markdown: "## Backend",
    },
    {
      id: "fastapi",
      kind: "note",
      icon: { src: "/icons/tech/fastapi.svg", alt: "FastAPI" },
      layer: "background",
      order: 10,
      x: architectureX(29.5),
      y: architectureY(22),
      width: 24,
      height: 230,
      markdown: "**FastAPI**\n\nKnowledge API",
    },
    {
      id: "mcp",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/mcp.svg", alt: "Model Context Protocol" },
      order: 12,
      x: architectureX(42),
      y: architectureY(31),
      width: 11,
      markdown: "**MCP Server**\n\nFastAPI-MCP",
    },
    {
      id: "sqlalchemy",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/sqlalchemy.svg", alt: "SQLAlchemy" },
      order: 11,
      x: architectureX(30),
      y: architectureY(31),
      width: 11,
      markdown: "**SQLAlchemy**\n\nData Access / ORM",
    },
    {
      id: "qdrant",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/qdrant.svg", alt: "Qdrant" },
      order: 14,
      x: architectureX(42),
      y: architectureY(43),
      width: 11,
      markdown: "**Qdrant**\n\nVector Index",
    },
    {
      id: "database",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/database.svg", alt: "Database" },
      order: 13,
      x: architectureX(30),
      y: architectureY(43),
      width: 11,
      markdown: "**Database**\n\nKnowledge Metadata",
    },
    {
      id: "mcp-clients-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/tech/mcp.svg", alt: "MCP Clients" },
      excludeFromSequence: true,
      x: architectureX(57),
      y: architectureY(14),
      width: 25,
      height: 260,
      markdown: "## MCP Clients",
    },
    {
      id: "claude",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/claude.svg", alt: "Claude" },
      order: 15,
      x: architectureX(58.5),
      y: architectureY(23),
      width: 6.8,
      markdown: "**Claude**",
    },
    {
      id: "cursor",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/cursor.svg", alt: "Cursor" },
      order: 16,
      x: architectureX(66.4),
      y: architectureY(23),
      width: 6.8,
      markdown: "**Cursor**",
    },
    {
      id: "openai",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/openai.svg", alt: "OpenAI Codex" },
      order: 17,
      x: architectureX(74.3),
      y: architectureY(23),
      width: 6.8,
      markdown: "**Codex**",
    },
    {
      id: "backend-mcp-description",
      kind: "note",
      appearance: "transparent",
      order: 18,
      x: architectureX(57),
      y: architectureY(36),
      width: 25,
      markdown:
        "**Knowledge CRUD를 제공하는 FastAPI 기반 백엔드입니다.**\n\n**FastAPI-MCP**를 통해 REST API를 **MCP(Model Context Protocol) 도구**로 동시에 제공하여 **AI Agent가 동일한 기능을 직접 호출**할 수 있도록 구성했습니다. 이를 통해 **Claude, Cursor, Codex** 등 MCP를 지원하는 다양한 AI 클라이언트에서 별도의 API 구현 없이 동일한 **Knowledge API**를 활용할 수 있습니다. 또한 **SQLAlchemy** 기반으로 다양한 데이터베이스를 지원하며, **Qdrant**를 활용한 **임베딩 기반 RAG 검색** 기능을 제공합니다.",
    },
    {
      id: "deploy-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/deploy.svg", alt: "Deploy" },
      excludeFromSequence: true,
      x: architectureX(28),
      y: architectureY(58),
      width: 38,
      height: 600,
      markdown: "## Deploy",
    },
    {
      id: "deploy-description",
      kind: "note",
      appearance: "transparent",
      order: 19,
      x: architectureX(4),
      y: architectureY(64),
      width: 22,
      markdown:
        "**로컬 개발 환경과 CI 환경에서 동일한 빌드 과정을 사용할 수 있도록 배포 파이프라인을 구성했습니다.**\n\n**Hatch**를 공통 빌드 엔트리로 사용하여 **Docker 이미지 생성**과 **GitHub Actions 기반 CI**를 일관되게 관리하며, 빌드 결과물은 **Docker Image, PyPI, GitHub Container Registry(GHCR)**에 자동 배포됩니다.",
    },
    {
      id: "hatch-script",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/hatch.svg", alt: "Hatch" },
      order: 20,
      x: architectureX(39.5),
      y: architectureY(65),
      width: 14,
      markdown: "**Hatch Script**\n\nShared Build Entry",
    },
    {
      id: "local-build",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/docker.svg", alt: "Docker" },
      order: 21,
      x: architectureX(31),
      y: architectureY(77),
      width: 14,
      markdown: "**Local Build**\n\nDocker Build",
    },
    {
      id: "github-actions",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/github-actions.svg", alt: "GitHub Actions" },
      order: 22,
      x: architectureX(47),
      y: architectureY(77),
      width: 14,
      markdown: "**GitHub Actions**\n\nCI Build",
    },
    {
      id: "docker-image",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/docker.svg", alt: "Docker image" },
      order: 23,
      x: architectureX(30),
      y: architectureY(89),
      width: 14,
      markdown: "**Docker Image**\n\nLocal",
    },
    {
      id: "pypi",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/pypi.svg", alt: "PyPI" },
      order: 24,
      x: architectureX(45),
      y: architectureY(89),
      width: 9,
      markdown: "**PyPI**\n\nPackage",
    },
    {
      id: "ghcr",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/github.svg", alt: "GitHub Container Registry" },
      order: 25,
      x: architectureX(55),
      y: architectureY(89),
      width: 10,
      markdown: "**GHCR**\n\nRegistry",
    },
    {
      id: "quick-start",
      title: "Quick Start",
      kind: "note",
      order: 5,
      x: 111,
      y: 15,
      width: 50,
      markdown:
        "## 실행 방법\n\n**1. 패키지 설치 및 실행**\n\n```bash\npip install hippobox\nhippobox run\n```\n\n**2. 백엔드 서버 실행**\n\n```bash\ncd src/backend\nuv sync\nuv run uvicorn hippobox.server:app --reload\n```\n\n**3. 프론트엔드 실행 및 빌드**\n\n```bash\ncd src/frontend\nnpm install\nnpm run dev\nnpm run dev:vite\nnpm run build\n```",
    },
    {
      id: "features-title",
      kind: "note",
      appearance: "transparent",
      order: 26,
      x: featuresX(0),
      y: featuresY(0),
      width: 30,
      markdown: "# Features",
    },
    {
      id: "feature-knowledge-ui",
      kind: "note",
      appearance: "feature",
      order: 28,
      x: featuresX(0),
      y: featuresY(36),
      width: 40,
      markdown:
        "## Knowledge UI\n\nHippoBox는 저장된 지식을 사람이 직접 관리할 수 있는 **Knowledge UI**를 제공합니다. 지식은 **Topic** 단위로 분류되고, 제목·태그·본문을 함께 저장할 수 있으며, 본문은 **Markdown 기반 지식**으로 관리됩니다.",
    },
    {
      id: "feature-knowledge-ui-image",
      kind: "note",
      appearance: "transparent",
      order: 27,
      x: featuresX(0),
      y: featuresY(5),
      width: 40,
      image: {
        src: "/images/hippobox-guide/step-6.png",
        alt: "HippoBox knowledge UI with topic and markdown knowledge entries",
        width: 1920,
        height: 1080,
        frame: "outline",
        frameHeight: 400,
        fit: "cover",
      },
      markdown: "",
    },
    {
      id: "feature-hippo-search",
      kind: "note",
      appearance: "feature",
      order: 30,
      x: featuresX(42),
      y: featuresY(36),
      width: 40,
      markdown:
        "## Hippo Search\n\n**Hippo Search(VDB)**는 저장된 지식을 임베딩한 뒤 의미 기반으로 검색하는 기능입니다. 단순 키워드 매칭이 아니라 질문의 의미와 가까운 지식을 찾아 **AI Agent가 필요한 컨텍스트**를 안정적으로 가져오도록 설계했습니다.",
    },
    {
      id: "feature-hippo-search-image",
      kind: "note",
      appearance: "transparent",
      order: 29,
      x: featuresX(42),
      y: featuresY(5),
      width: 40,
      image: {
        src: "/images/hippobox-guide/step-3.png",
        alt: "Hippo Search vector database search result",
        width: 1278,
        height: 170,
        frame: "outline",
        frameHeight: 400,
        fit: "contain",
      },
      markdown: "",
    },
    {
      id: "feature-mcp-crud",
      kind: "note",
      appearance: "feature",
      order: 32,
      x: featuresX(0),
      y: featuresY(79),
      width: 40,
      markdown:
        "## AI Agent Knowledge CRUD\n\nHippoBox는 **FastAPI-MCP**를 통해 Knowledge CRUD API를 **MCP Tool**로 제공합니다. Claude, Cursor, Codex 같은 MCP 클라이언트는 별도 전용 API 구현 없이 동일한 **Knowledge API**를 호출할 수 있습니다.",
    },
    {
      id: "feature-mcp-crud-image",
      kind: "note",
      appearance: "transparent",
      order: 31,
      x: featuresX(0),
      y: featuresY(48),
      width: 40,
      image: {
        src: "/images/hippobox-guide/step-4.png",
        alt: "HippoBox MCP setup guide for Claude Cursor and Codex",
        width: 1920,
        height: 1080,
        frame: "outline",
        frameHeight: 400,
        fit: "cover",
      },
      markdown: "",
    },
    {
      id: "feature-terminal-crud",
      kind: "note",
      appearance: "feature",
      order: 34,
      x: featuresX(42),
      y: featuresY(79),
      width: 40,
      markdown:
        "## Terminal Workflow\n\nMCP 클라이언트에서 HippoBox 도구를 호출하면 Agent가 Knowledge API를 통해 실제 지식 항목을 생성하고 결과를 반환합니다. 터미널 출력에서는 **Frontend / Backend 지식 항목 생성 흐름**을 확인할 수 있습니다.",
    },
    {
      id: "feature-terminal-crud-image",
      kind: "note",
      appearance: "transparent",
      order: 33,
      x: featuresX(42),
      y: featuresY(48),
      width: 40,
      image: {
        src: "/images/hippobox-guide/step-5_2.png",
        alt: "HippoBox terminal output showing created knowledge entries",
        width: 556,
        height: 119,
        frame: "outline",
        frameHeight: 400,
        fit: "contain",
      },
      markdown: "",
    },
    {
      id: "project-results",
      kind: "note",
      appearance: "transparent",
      order: 35,
      x: outcomeX(0),
      y: outcomeY(0),
      width: 40,
      markdown:
        "# Results\n\n**사람과 AI가 하나의 Knowledge Base를 함께 사용할 수 있도록 만들었습니다.**\n\nHippoBox는 제가 처음 목표로 했던 **Local-first Knowledge Platform**을 실제로 구현한 프로젝트입니다. **Markdown 기반**으로 지식을 관리하고, **MCP**를 통해 AI Agent와 연결하며, **Semantic Search**를 통해 필요한 지식을 의미 기반으로 찾을 수 있도록 구성했습니다.\n\n사용자는 하나의 **Knowledge Base**만 관리하면 되고, **Claude, Cursor, Codex** 같은 AI Agent는 동일한 **Knowledge API**를 통해 같은 지식을 활용할 수 있습니다. 사람이 관리한 지식을 AI도 자연스럽게 활용하는 환경을 만드는 것이 HippoBox의 가장 큰 결과였습니다.",
    },
    {
      id: "lesson-learned",
      kind: "note",
      appearance: "transparent",
      order: 36,
      x: outcomeX(50),
      y: outcomeY(0),
      width: 40,
      markdown:
        "# Lessons Learned\n\n**AI 기능을 만드는 것보다 AI가 활용하기 쉬운 구조를 만드는 것이 더 중요했습니다.**\n\nHippoBox를 개발하면서 **FastAPI 기반 백엔드**, **MCP 서버**, 그리고 **RAG 기반 Semantic Search**를 직접 설계하고 구현하며 AI 친화적인 서비스 구조를 고민할 수 있었습니다.\n\n또 하나 크게 느낀 점은 에이전틱 코딩을 반복적으로 활용하려면 프로젝트를 처음부터 다시 만드는 것이 아니라, 인증, 배포, 프로젝트 구조 같은 기반이 미리 준비되어 있어야 한다는 것이었습니다. 그래서 HippoBox에서 얻은 경험을 바탕으로 AI 애플리케이션을 빠르게 시작할 수 있는 **Blueprint4Agent(B4A)** 프로젝트를 이어서 개발하게 되었습니다.",
    },
  ];

  return {
    nodes: [
      {
        id: "summary",
        kind: "note",
        appearance: "transparent",
        order: 1,
        x: 26,
        y: 8,
        width: 50,
        markdown: [
          "# HippoBox",
          "",
          "**HippoBox는 개인 지식을 체계적으로 관리하고 AI Agent가 활용할 수 있도록 설계한 Knowledge Management Platform입니다.**",
          "",
          "**FastAPI와 FastAPI-MCP**를 기반으로 구축한 통합 지식 관리 서비스로, 지식 항목에 대한 **CRUD(Create, Read, Update, Delete)**, 임베딩 기반 **Semantic Search**, **MCP(Model Context Protocol) Tool Integration**을 제공합니다. 이를 통해 **Claude, Cursor, Codex** 등 MCP를 지원하는 다양한 AI 클라이언트에서 동일한 **Knowledge API**를 일관된 방식으로 활용할 수 있습니다.",
          "",
          "이 페이지에서는 HippoBox를 개발하게 된 목표와 시스템 아키텍처, 주요 기능 및 구현 과정, 그리고 프로젝트를 통해 얻은 결과와 경험을 소개합니다.",
        ].join("\n"),
      },
      {
        id: "project-icon",
        kind: "note",
        appearance: "transparent",
        excludeFromSequence: true,
        x: 13,
        y: 7,
        width: 10,
        image: {
          src: "/hippobox.svg",
          alt: "HippoBox icon",
          width: 120,
          height: 120,
          frame: "plain",
        },
        markdown: "",
      },
      {
        id: "github-status",
        title: "Info",
        kind: "note",
        order: 2,
        x: 82,
        y: 10,
        width: 24,
        markdown: [
          "- :calendar: 2025.11 ~ 2026.2",
          "- :stack: `FastAPI` `TypeScript` `MCP` `Qdrant`",
          "",
          `- :github: [GitHub|HippoBox GitHub 저장소로 이동](${project.href})`,
          "- :package: [PyPI|HippoBox PyPI 패키지로 이동](https://pypi.org/project/hippobox/)",
        ].join("\n"),
      },
      {
        id: "project-goals",
        kind: "note",
        appearance: "transparent",
        order: 3,
        x: 13,
        y: 37,
        width: 43,
        markdown: [
          "# Project Goals",
          "",
          "**AI가 활용할 수 있는 지식은 사람도 쉽게 관리할 수 있어야 합니다.**",
          "",
          "AI 도구가 늘어날수록 지식은 여러 서비스에 분산되고, 같은 내용을 반복해서 관리해야 하는 문제가 발생합니다.",
          "",
          "HippoBox는 하나의 **Knowledge Base**를 중심으로 사람과 AI가 동일한 지식을 함께 활용할 수 있는 환경을 목표로 시작한 프로젝트입니다.",
          "",
          "이를 위해 **FastAPI 기반의 Knowledge CRUD 서비스**를 구축하고, **FastAPI-MCP**를 통해 동일한 기능을 **MCP(Model Context Protocol) Tool**로 제공합니다. 또한 **Qdrant 기반의 임베딩 검색**을 적용하여 AI가 단순 키워드가 아닌 **의미 기반으로 지식을 검색하고 활용**할 수 있도록 설계했습니다.",
        ].join("\n"),
      },
      {
        id: "project-goals-list",
        title: "Goals",
        kind: "note",
        order: 4,
        x: 58,
        y: 42,
        width: 27,
        markdown: [
          "",
          "- Local-first Knowledge Platform",
          "- Markdown 기반 지식 관리",
          "- MCP 기반 AI Agent 연동",
          "- Semantic Search 제공",
          "- 확장 가능한 Backend Architecture",
        ].join("\n"),
      },
      ...architectureNodes,
    ],
    edges: hippoboxArchitectureEdges,
  };
}
