import type { CanvasEdge, CanvasNode } from "@/components/canvas/workflow-canvas";
import type { Project } from "@/types/project";
import type { ProjectDetailCanvasDefinition } from "./types";

export function getSayItOkDetailCanvas(project: Project): ProjectDetailCanvasDefinition {
  const architectureOrigin = { x: 13, y: 62 };
  const architectureX = (x: number) => architectureOrigin.x + x;
  const architectureY = (y: number) => architectureOrigin.y + y;
  const featuresOrigin = { x: 88, y: 62 };
  const featuresX = (x: number) => featuresOrigin.x + x;
  const featuresY = (y: number) => featuresOrigin.y + y;
  const outcomeOrigin = { x: 13, y: 150 };
  const outcomeX = (x: number) => outcomeOrigin.x + x;
  const outcomeY = (y: number) => outcomeOrigin.y + y;

  const nodes: CanvasNode[] = [
    {
      id: "project-icon",
      kind: "note",
      appearance: "transparent",
      excludeFromSequence: true,
      x: 13,
      y: 7,
      width: 10,
      image: {
        src: "/say-it-ok.png",
        alt: "말하면 OK icon",
        width: 120,
        height: 120,
        frame: "plain",
      },
      markdown: "",
    },
    {
      id: "summary",
      kind: "note",
      appearance: "transparent",
      order: 1,
      x: 26,
      y: 8,
      width: 50,
      markdown:
        "**말하면 OK는 실제 직원처럼 사용자의 자연어 요청을 이해하고 응답하는 AI Voice Kiosk입니다.**\n\nSTT(Speech-to-Text)부터 의도 분석, 주문·추천·안내, TTS(Text-to-Speech) 응답까지 하나의 AI 파이프라인으로 구성하여 사람과 대화하듯 자연스러운 키오스크 경험을 제공합니다.",
    },
    {
      id: "info",
      title: "Info",
      kind: "note",
      order: 2,
      x: 79,
      y: 10,
      width: 24,
      markdown: [
        "- :calendar: 2025.3 ~ 2025.6",
        "- :stack: `React` `Node.js` `FastAPI` `OpenAI` `STT` `TTS`",
        "",
        `- :github: [GitHub|말하면 OK GitHub 조직으로 이동](${project.href})`,
      ].join("\n"),
    },
    {
      id: "project-goals",
      kind: "note",
      appearance: "transparent",
      order: 3,
      x: 13,
      y: 35,
      width: 47,
      markdown:
        "# Project Goals\n\n**사용자가 키오스크를 조작법이 아니라 자연어 대화로 사용할 수 있어야 합니다.**\n\n기존 키오스크는 화면 구조를 알고 직접 탐색해야 하지만, 말하면 OK는 직원에게 말하듯 요청하면 주문, 추천, 안내 같은 행동으로 이어지는 경험을 목표로 했습니다.\n\n음성 입력을 텍스트로 바꾸고, 자연어 의도를 분석한 뒤, 키오스크 API와 TTS 응답으로 연결하는 end-to-end 파이프라인을 구성했습니다.",
    },
    {
      id: "goals-list",
      title: "Goals",
      kind: "note",
      order: 4,
      x: 64,
      y: 42,
      width: 30,
      markdown: [
        "",
        "- 음성 기반 키오스크 인터랙션",
        "- STT 기반 자연어 입력 처리",
        "- OpenAI 기반 의도 분석",
        "- 주문·추천·안내 API 연동",
        "- TTS 기반 응답 경험",
      ].join("\n"),
    },
    {
      id: "quick-start",
      title: "Quick Start",
      kind: "note",
      order: 5,
      x: 100,
      y: 16,
      width: 40,
      markdown:
        "## Client / STT\n\n```bash\nnpm install\nnpm run dev\n```\n\n## API Server\n\n```bash\nnpm install\nnpm run dev\nnode app.js\n```\n\n## NLP Server\n\n```bash\npython3 -m venv .venv\nsource .venv/bin/activate\npip install -r requirements.txt\nuvicorn app.main:app --reload --port=3002\n```",
    },
    {
      id: "architecture-title",
      kind: "note",
      appearance: "transparent",
      order: 6,
      x: architectureX(0),
      y: architectureY(0),
      width: 34,
      markdown: "# System Architecture",
    },
    {
      id: "client-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/frontend.svg", alt: "Client" },
      excludeFromSequence: true,
      x: architectureX(0),
      y: architectureY(7),
      width: 24,
      height: 250,
      markdown: "## Client",
    },
    {
      id: "server-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/backend.svg", alt: "Server" },
      excludeFromSequence: true,
      x: architectureX(30),
      y: architectureY(7),
      width: 26,
      height: 330,
      markdown: "## API / NLP",
    },
    {
      id: "voice-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/tech/google-cloud.svg", alt: "Voice" },
      excludeFromSequence: true,
      x: architectureX(61),
      y: architectureY(7),
      width: 23,
      height: 250,
      markdown: "## Voice / AI",
    },
    {
      id: "react",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/react.svg", alt: "React" },
      order: 7,
      x: architectureX(3),
      y: architectureY(20),
      width: 10,
      markdown: "**React**",
    },
    {
      id: "typescript",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/typescript.svg", alt: "TypeScript" },
      order: 8,
      x: architectureX(14),
      y: architectureY(20),
      width: 8,
      markdown: "**TS**",
    },
    {
      id: "node-api",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/nodejs.svg", alt: "Node.js" },
      order: 9,
      x: architectureX(33),
      y: architectureY(20),
      width: 10,
      markdown: "**Node API**",
    },
    {
      id: "fastapi-nlp",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/fastapi.svg", alt: "FastAPI" },
      order: 10,
      x: architectureX(44),
      y: architectureY(20),
      width: 10,
      markdown: "**FastAPI NLP**",
    },
    {
      id: "database",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/database.svg", alt: "MongoDB" },
      order: 11,
      x: architectureX(38),
      y: architectureY(37),
      width: 10,
      markdown: "**MongoDB**",
    },
    {
      id: "stt",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/google-cloud.svg", alt: "STT" },
      order: 12,
      x: architectureX(63),
      y: architectureY(20),
      width: 9,
      markdown: "**STT**",
    },
    {
      id: "openai",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/openai.svg", alt: "OpenAI" },
      order: 13,
      x: architectureX(73),
      y: architectureY(20),
      width: 9,
      markdown: "**OpenAI**",
    },
    {
      id: "tts",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/google-cloud.svg", alt: "TTS" },
      order: 14,
      x: architectureX(68),
      y: architectureY(37),
      width: 9,
      markdown: "**TTS**",
    },
    {
      id: "features-title",
      kind: "note",
      appearance: "transparent",
      order: 15,
      x: featuresX(0),
      y: featuresY(0),
      width: 30,
      markdown: "# Features",
    },
    ...[
      ["feature-stt", "STT Pipeline", "사용자의 음성 요청을 텍스트로 변환하고, 이후 자연어 처리 서버가 이해할 수 있는 입력으로 전달합니다."],
      ["feature-intent", "Intent Analysis", "OpenAI 기반 NLP 서버가 주문, 추천, 안내 같은 사용자의 의도를 분석하고 API 서버로 전달합니다."],
      ["feature-kiosk", "Kiosk Actions", "Node.js API 서버가 메뉴 조회, 추천, 주문, 장바구니 변경 같은 키오스크 행동을 수행합니다."],
      ["feature-tts", "TTS Response", "처리 결과를 음성 응답으로 다시 전달해 사용자가 화면을 직접 탐색하지 않아도 대화 흐름을 유지할 수 있게 합니다."],
    ].map(([id, title, body], index) => ({
      id,
      kind: "note" as const,
      appearance: "feature" as const,
      order: 16 + index,
      x: featuresX(index % 2 === 0 ? 0 : 42),
      y: featuresY(10 + Math.floor(index / 2) * 22),
      width: 38,
      markdown: `## ${title}\n\n${body}`,
    })),
    {
      id: "results",
      kind: "note",
      appearance: "transparent",
      order: 20,
      x: outcomeX(0),
      y: outcomeY(0),
      width: 40,
      markdown:
        "# Results\n\n**음성 인식부터 자연어 이해, 키오스크 행동, 음성 응답까지 이어지는 AI Voice Kiosk 흐름을 구현했습니다.**\n\n사용자는 직원에게 말하듯 요청할 수 있고, 시스템은 요청 의도를 분석해 메뉴 추천, 주문, 안내 같은 행동으로 연결합니다. 팀 프로젝트 범위 안에서 프론트엔드, API 서버, NLP 서버, STT/TTS 흐름을 분리해 구성했습니다.",
    },
    {
      id: "lessons",
      kind: "note",
      appearance: "transparent",
      order: 21,
      x: outcomeX(44),
      y: outcomeY(4),
      width: 40,
      markdown:
        "# Lessons Learned\n\n**AI 음성 서비스는 모델 호출보다 입력·상태·응답 흐름을 안정적으로 연결하는 것이 중요했습니다.**\n\n이 프로젝트를 통해 음성 입력 처리, 자연어 의도 분석, API 서버와의 역할 분리, TTS 응답 설계, 키오스크 도메인 행동 모델링을 경험했습니다.",
    },
  ];

  return {
    nodes,
    edges: [
      {
        id: "client-to-server",
        from: { nodeId: "client-section", side: "right" },
        to: { nodeId: "server-section", side: "left" },
        bidirectional: true,
      },
      {
        id: "server-to-voice",
        from: { nodeId: "server-section", side: "right" },
        to: { nodeId: "voice-section", side: "left" },
        bidirectional: true,
      },
      {
        id: "nlp-to-openai",
        from: { nodeId: "fastapi-nlp", side: "right" },
        to: { nodeId: "openai", side: "left" },
        bidirectional: true,
      },
      {
        id: "api-to-database",
        from: { nodeId: "node-api", side: "bottom" },
        to: { nodeId: "database", side: "top" },
        bidirectional: true,
      },
    ],
  };
}
