import type { CanvasEdge, CanvasNode } from "@/components/canvas/workflow-canvas";
import type { Project } from "@/types/project";
import type { ProjectDetailCanvasDefinition } from "./types";

const sayItOkArchitectureEdges: CanvasEdge[] = [
  {
    id: "client-to-voice",
    from: { nodeId: "client-section", side: "right" },
    to: { nodeId: "voice-section", side: "left" },
    bidirectional: true,
  },
  {
    id: "client-to-api",
    from: { nodeId: "client-section", side: "bottom" },
    to: { nodeId: "api-server", side: "left" },
    bidirectional: true,
  },
  {
    id: "voice-to-nlp",
    from: { nodeId: "voice-section", side: "right" },
    to: { nodeId: "nlp-section", side: "left" },
    bidirectional: true,
  },
  {
    id: "nlp-to-api",
    from: { nodeId: "nlp-server", side: "left" },
    to: { nodeId: "api-server", side: "right" },
    directed: true,
  },
  {
    id: "api-to-database",
    from: { nodeId: "api-server", side: "bottom" },
    to: { nodeId: "database", side: "top" },
    bidirectional: true,
  },
  {
    id: "nlp-to-openai",
    from: { nodeId: "nlp-server", side: "bottom" },
    to: { nodeId: "openai", side: "top" },
    bidirectional: true,
  },
  {
    id: "api-to-voice",
    from: { nodeId: "api-server", side: "top" },
    to: { nodeId: "voice-section", side: "bottom" },
    directed: true,
  },
];

export function getSayItOkDetailCanvas(
  project: Project,
): ProjectDetailCanvasDefinition {
  const architectureOrigin = { x: 13, y: 64 };
  const architectureX = (x: number) => architectureOrigin.x + x;
  const architectureY = (y: number) => architectureOrigin.y + y;
  const featuresOrigin = { x: 101, y: 64 };
  const featuresX = (x: number) => featuresOrigin.x + x;
  const featuresY = (y: number) => featuresOrigin.y + y;
  const outcomeOrigin = { x: 93, y: 125 };
  const outcomeX = (x: number) => outcomeOrigin.x + x;
  const outcomeY = (y: number) => outcomeOrigin.y + y;

  const architectureNodes: CanvasNode[] = [
    {
      id: "architecture-title",
      kind: "note",
      appearance: "transparent",
      order: 5,
      x: architectureX(0),
      y: architectureY(0),
      width: 34,
      markdown: "# System Architecture",
    },
    {
      id: "client-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/frontend.svg", alt: "Client" },
      excludeFromSequence: true,
      x: architectureX(0),
      y: architectureY(7),
      width: 23,
      height: 260,
      markdown: "## Client",
    },
    {
      id: "react",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/react.svg", alt: "React" },
      order: 6,
      x: architectureX(2),
      y: architectureY(16),
      width: 9.5,
      markdown: "**React**",
    },
    {
      id: "typescript",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/typescript.svg", alt: "TypeScript" },
      order: 7,
      x: architectureX(12),
      y: architectureY(16),
      width: 9.5,
      markdown: "**TypeScript**",
    },
    {
      id: "voice-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/tech/google-cloud.svg", alt: "STT and TTS" },
      excludeFromSequence: true,
      x: architectureX(27),
      y: architectureY(7),
      width: 23,
      height: 260,
      markdown: "## STT / Voice",
    },
    {
      id: "stt-server",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/google-cloud.svg", alt: "STT Server" },
      order: 8,
      x: architectureX(29),
      y: architectureY(16),
      width: 9.5,
      markdown: "**STT Server**\n\nVoice to Text",
    },
    {
      id: "tts-response",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/google-cloud.svg", alt: "TTS Response" },
      order: 9,
      x: architectureX(39),
      y: architectureY(16),
      width: 9.5,
      markdown: "**TTS Response**\n\nVoice Feedback",
    },
    {
      id: "nlp-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/tech/fastapi.svg", alt: "NLP Server" },
      excludeFromSequence: true,
      x: architectureX(54),
      y: architectureY(7),
      width: 17,
      height: 260,
      markdown: "## NLP Server",
    },
    {
      id: "nlp-server",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/fastapi.svg", alt: "FastAPI NLP Server" },
      order: 10,
      x: architectureX(56),
      y: architectureY(16),
      width: 13,
      markdown: "**NLP Server**\n\nIntent Analysis",
    },
    {
      id: "openai",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/openai.svg", alt: "OpenAI" },
      order: 12,
      x: architectureX(56),
      y: architectureY(30),
      width: 13,
      markdown: "**OpenAI**",
    },
    {
      id: "api-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/backend.svg", alt: "API Server" },
      excludeFromSequence: true,
      x: architectureX(30),
      y: architectureY(28),
      width: 17,
      height: 430,
      markdown: "## API Server",
    },
    {
      id: "api-server",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/nodejs.svg", alt: "Node.js API Server" },
      order: 11,
      x: architectureX(32),
      y: architectureY(37),
      width: 13,
      markdown: "**API Server**\n\nKiosk Actions",
    },
    {
      id: "database",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/mongodb.svg", alt: "MongoDB" },
      order: 13,
      x: architectureX(32),
      y: architectureY(48),
      width: 13,
      markdown: "**MongoDB**\n\nMenu / Order",
    },
    {
      id: "client-voice-api-description",
      kind: "note",
      appearance: "transparent",
      order: 14,
      x: architectureX(2),
      y: architectureY(40),
      width: 20,
      markdown:
        "**화면과 음성, 두 가지 인터랙션을 하나의 키오스크 경험으로 통합했습니다.**\n\nReact 기반 클라이언트는 기존 키오스크처럼 화면을 직접 조작하는 방식과 음성으로 요청하는 방식을 모두 지원합니다. 음성 입력은 **Google Cloud Speech-to-Text(STT)** 서비스를 통해 텍스트로 변환되고, 처리 결과는 **Google Cloud Text-to-Speech(TTS)** 서비스를 통해 다시 음성으로 전달됩니다. 화면 입력과 음성 입력은 모두 Node.js 기반 API 서버를 통해 동일한 메뉴 조회, 추천, 주문 기능을 수행하며, API 서버는 MongoDB와 연동하여 메뉴와 주문 정보를 관리합니다. 이를 통해 사용자는 상황에 따라 **터치 기반 또는 음성 기반으로 동일한 키오스크 서비스를 이용할 수 있도록 구성했습니다.**",
    },
    {
      id: "voice-nlp-api-description",
      kind: "note",
      appearance: "transparent",
      order: 14,
      x: architectureX(53),
      y: architectureY(40),
      width: 20,
      markdown:
        "**자연어를 키오스크가 이해할 수 있는 행동으로 변환하는 AI 계층입니다.**\n\nFastAPI 기반 NLP 서버는 STT를 통해 전달된 텍스트와 화면 입력에서 전달된 요청을 **OpenAI를 활용해 분석하고, 주문, 추천, 안내 등 사용자의 의도를 키오스크 도메인에 맞는 행동으로 변환합니다.** **분석된 결과는 API 서버로 전달되어 실제 메뉴 조회, 추천, 주문 기능을 수행**하며, 각 계층은 독립적인 역할을 유지하면서도 인터랙티브하게 연결되어 **하나의 end-to-end AI Voice Kiosk 경험을 제공합니다.**",
    },
  ];

  const nodes: CanvasNode[] = [
    {
      id: "project-icon",
      kind: "note",
      appearance: "transparent",
      excludeFromSequence: true,
      x: 13,
      y: 7,
      width: 10,
      image: {
        src: "/say-it-ok.png",
        alt: "말하면 OK icon",
        width: 120,
        height: 120,
        frame: "plain",
      },
      markdown: "",
    },
    {
      id: "summary",
      kind: "note",
      appearance: "transparent",
      order: 1,
      x: 26,
      y: 8,
      width: 50,
      markdown:
        "# 말하면 OK\n\n**말하면 OK는 실제 직원처럼 사용자의 자연어 요청을 이해하고 응답하는 AI Voice Kiosk입니다.**\n\n이 프로젝트는 `client`, `server`, `stt`, `nlp`처럼 역할별 저장소를 분리해 구성한 팀 프로젝트입니다. 클라이언트, STT 서버, API 서버, 자연어 처리 서버가 각각 독립된 역할을 담당하며, 사용자의 음성 요청을 **주문·추천·안내 같은 키오스크 행동**으로 연결하는 구조를 목표로 했습니다.",
    },
    {
      id: "info",
      title: "Info",
      kind: "note",
      order: 2,
      x: 79,
      y: 10,
      width: 24,
      markdown: [
        "- :calendar: 2025.3 ~ 2025.6",
        "- :stack: `React` `TypeScript` `Node.js` `FastAPI` `STT` `TTS`",
        "",
        `- :github: [GitHub|말하면 OK GitHub 조직으로 이동](${project.href})`,
      ].join("\n"),
    },
    {
      id: "project-goals",
      kind: "note",
      appearance: "transparent",
      order: 3,
      x: 13,
      y: 35,
      width: 48,
      markdown:
        "# Project Goals\n\n**사용자가 키오스크를 조작법이 아니라 자연어 대화로 사용할 수 있어야 합니다.**\n\n기존 키오스크는 사용자가 화면 구조를 이해하고 직접 메뉴를 탐색해야 합니다. 말하면 OK는 사용자가 직원에게 말하듯 요청하면, 시스템이 음성을 이해하고 필요한 행동으로 연결하는 경험을 목표로 시작했습니다.\n\n이를 위해 클라이언트, STT 서버, API 서버, NLP 서버를 분리하고, 음성 입력부터 자연어 의도 분석, 키오스크 행동 수행, 음성 응답까지 이어지는 **end-to-end 파이프라인**을 구성했습니다.",
    },
    {
      id: "goals-list",
      title: "Goals",
      kind: "note",
      order: 4,
      x: 66,
      y: 42,
      width: 33,
      markdown: [
        "",
        "- 음성 기반 키오스크 인터랙션",
        "- STT 기반 자연어 입력 처리",
        "- NLP 서버 기반 의도 분석",
        "- 메뉴 조회·추천·주문 API 연동",
        "- TTS 기반 음성 응답 경험",
      ].join("\n"),
    },
    ...architectureNodes,
    {
      id: "features-title",
      kind: "note",
      appearance: "transparent",
      order: 15,
      x: featuresX(0),
      y: featuresY(0),
      width: 30,
      markdown: "# Features",
    },
    {
      id: "feature-stt",
      kind: "note",
      appearance: "feature",
      order: 16,
      x: featuresX(0),
      y: featuresY(7),
      width: 40,
      markdown:
        "## STT Pipeline\n\n사용자의 **음성 요청을 텍스트로 변환**하고, 자연어 처리 서버가 이해할 수 있는 입력으로 전달합니다.",
    },
    {
      id: "feature-intent",
      kind: "note",
      appearance: "feature",
      order: 17,
      x: featuresX(42),
      y: featuresY(7),
      width: 40,
      markdown:
        "## Intent Analysis\n\nNLP 서버가 사용자의 요청 의도를 분석하여 **주문, 추천, 안내** 같은 키오스크 행동으로 분류합니다.",
    },
    {
      id: "feature-kiosk",
      kind: "note",
      appearance: "feature",
      order: 18,
      x: featuresX(0),
      y: featuresY(30),
      width: 40,
      markdown:
        "## Kiosk Actions\n\nAPI 서버가 **메뉴 조회, 추천, 주문, 장바구니 변경** 등 실제 키오스크 기능을 수행합니다.",
    },
    {
      id: "feature-tts",
      kind: "note",
      appearance: "feature",
      order: 19,
      x: featuresX(42),
      y: featuresY(30),
      width: 40,
      markdown:
        "## TTS Response\n\n처리 결과를 음성으로 다시 전달하여 사용자가 화면을 직접 탐색하지 않아도 **대화 흐름**을 이어갈 수 있도록 구성했습니다.",
    },
    {
      id: "results",
      kind: "note",
      appearance: "transparent",
      order: 20,
      x: outcomeX(0),
      y: outcomeY(0),
      width: 42,
      markdown:
        "# Results\n\n**음성 요청이 실제 키오스크 행동으로 이어지는 흐름을 구현했습니다.**\n\n말하면 OK는 사용자의 음성 입력부터 STT, 자연어 의도 분석, API 서버 처리, TTS 응답까지 이어지는 **AI Voice Kiosk 파이프라인**을 구현한 프로젝트입니다.\n\n저는 팀 프로젝트 안에서 클라이언트, STT 서버, API 서버, NLP 서버를 역할별로 분리하고, 각 서버가 하나의 사용자 요청 흐름 안에서 연결되도록 구성했습니다. 이를 통해 사용자는 직원에게 말하듯 요청하고, 시스템은 이를 메뉴 추천, 주문, 안내 같은 행동으로 처리할 수 있는 구조를 만들었습니다.",
    },
    {
      id: "lessons",
      kind: "note",
      appearance: "transparent",
      order: 21,
      x: outcomeX(50),
      y: outcomeY(0),
      width: 42,
      markdown:
        "# Lessons Learned\n\n**AI 음성 서비스는 모델보다 흐름을 안정적으로 연결하는 것이 중요했습니다.**\n\n이 프로젝트를 통해 음성 입력, 자연어 처리, API 서버, 화면 상태, 음성 응답이 하나의 사용자 경험으로 연결되어야 한다는 점을 경험했습니다.\n\n특히 STT와 NLP 결과가 아무리 좋아도, API 서버의 행동 모델과 클라이언트 상태가 일관되지 않으면 자연스러운 키오스크 경험을 만들기 어렵다는 것을 알게 되었습니다. 말하면 OK는 AI 기능을 단순히 붙이는 것이 아니라, 음성 입력이 실제 서비스 행동으로 이어지도록 전체 파이프라인을 설계한 경험이었습니다.",
    },
  ];

  return {
    nodes,
    edges: sayItOkArchitectureEdges,
  };
}
