import type { CanvasNode } from "@/components/canvas/workflow-canvas";
import type { Project } from "@/types/project";
import type { ProjectDetailCanvasDefinition } from "./types";

export function getTodayInTechDetailCanvas(
  project: Project,
): ProjectDetailCanvasDefinition {
  const architectureOrigin = { x: 13, y: 62 };
  const architectureX = (x: number) => architectureOrigin.x + x;
  const architectureY = (y: number) => architectureOrigin.y + y;
  const featuresOrigin = { x: 104, y: 62 };
  const featuresX = (x: number) => featuresOrigin.x + x;
  const featuresY = (y: number) => featuresOrigin.y + y;
  const outcomeOrigin = { x: 13, y: 178 };
  const outcomeX = (x: number) => outcomeOrigin.x + x;
  const outcomeY = (y: number) => outcomeOrigin.y + y;

  const nodes: CanvasNode[] = [
    {
      id: "project-icon",
      kind: "note",
      appearance: "transparent",
      excludeFromSequence: true,
      x: 13,
      y: 7,
      width: 10,
      image: {
        src: "/today-in-tech.svg",
        alt: "Today in Tech icon",
        width: 120,
        height: 120,
        frame: "plain",
      },
      markdown: "",
    },
    {
      id: "summary",
      kind: "note",
      appearance: "transparent",
      order: 1,
      x: 26,
      y: 8,
      width: 50,
      markdown:
        "# Today in Tech\n\n**Today in Tech는 기술 뉴스와 공식 기술 블로그의 중요한 흐름만 선별하여 지속적으로 축적하는 AI 기반 기술 아카이브입니다.**\n\n하나의 파이프라인을 통해 **RSS/Atom Feed와 공식 Sitemap**을 기반으로 최신 기술 콘텐츠를 수집하고, AI를 활용해 의미 있는 글을 문서로 정리합니다. 생성된 문서는 **Docusaurus** 기반 아카이브 사이트에 자동 배포되어 기술의 흐름을 지속적으로 기록하는 **Knowledge Archive**를 구성합니다.\n\n이 페이지에서는 Today in Tech를 개발하게 된 목표와 시스템 아키텍처, 주요 기능 및 구현 과정, 그리고 프로젝트를 통해 얻은 결과와 경험을 소개합니다.",
    },
    {
      id: "info",
      title: "Info",
      kind: "note",
      order: 2,
      x: 79,
      y: 10,
      width: 24,
      markdown: [
        "- :calendar: 2026.5 ~ In Progress",
        "- :stack: `OpenAI Agent` `Docusaurus` `GitHub Actions`",
        "",
        `- :github: [GitHub|Today in Tech GitHub 저장소로 이동](${project.href})`,
        "- :website: [Website|Today in Tech 사이트로 이동](https://todayintech.github.io/todayintech/)",
      ].join("\n"),
    },
    {
      id: "project-goals",
      kind: "note",
      appearance: "transparent",
      order: 3,
      x: 13,
      y: 35,
      width: 47,
      markdown:
        "# Project Goals\n\n**기술 정보는 빠르게 소비되지만, 지식은 오래 남아야 합니다.**\n\n매일 수많은 기술 뉴스와 공식 블로그가 공개되지만, 여러 사이트를 직접 확인하고 중요한 내용을 정리하는 데는 많은 시간이 필요합니다. 시간이 지나면 과거의 기술 흐름을 다시 찾아보거나 특정 기술이 어떻게 발전했는지 추적하는 것도 쉽지 않습니다.\n\nToday in Tech는 이러한 문제를 해결하기 위해 시작한 프로젝트입니다. 콘텐츠를 자동으로 수집하고, AI가 의미 있는 글만 선별하여 하나의 기술 아카이브로 축적하는 것을 목표로 했습니다. 단순한 뉴스 요약이 아니라 기술의 흐름을 장기적으로 기록하고 검색할 수 있는 Knowledge Archive를 지향합니다.",
    },
    {
      id: "goals-list",
      title: "Goals",
      kind: "note",
      order: 4,
      x: 64,
      y: 42,
      width: 30,
      markdown: [
        "",
        "- 공식 기술 콘텐츠 자동 수집",
        "- 중복 제거 및 후보 전처리",
        "- Evidence 기반 원문 분석",
        "- AI Writer 기반 문서 생성",
        "- Docusaurus 기반 기술 아카이브 구축",
      ].join("\n"),
    },
    {
      id: "quick-start",
      title: "Quick Start",
      kind: "note",
      order: 5,
      x: 100,
      y: 16,
      width: 40,
      markdown:
        "```bash\npython3 -m venv .venv\n.venv/bin/python -m pip install -e .\nnpm install\n```\n\n```bash\nmake collect\nmake preprocess\nmake enrich\nmake write\nmake build\nmake serve\n```\n\n```bash\nOPENAI_API_KEY=sk-... make generate-openai\nmake deploy\n```",
    },
    {
      id: "architecture-title",
      kind: "note",
      appearance: "transparent",
      order: 6,
      x: architectureX(0),
      y: architectureY(0),
      width: 34,
      markdown: "# System Architecture",
    },
    {
      id: "sources-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/frontend.svg", alt: "Sources" },
      excludeFromSequence: true,
      x: architectureX(0),
      y: architectureY(7),
      width: 31,
      height: 500,
      markdown: "## Sources",
    },
    ...[
      {
        id: "source-openai",
        title: "OpenAI",
        icon: "/images/today-in-tech-services/openai-blog.svg",
        x: 1,
        y: 17,
      },
      {
        id: "source-anthropic",
        title: "Anthropic",
        icon: "/images/today-in-tech-services/anthropic-blog.svg",
        x: 11,
        y: 17,
      },
      {
        id: "source-google",
        title: "Google",
        icon: "/images/today-in-tech-services/google-blog.svg",
        x: 21,
        y: 17,
      },
      {
        id: "source-github",
        title: "GitHub",
        icon: "/images/today-in-tech-services/github-blog.svg",
        x: 5.5,
        y: 31,
      },
      {
        id: "source-hacker-news",
        title: "Hacker News",
        icon: "/images/today-in-tech-services/hacker-news.svg",
        x: 15.5,
        y: 31,
      },
    ].map(({ id, title, icon, x, y }, index) => ({
      id,
      kind: "note" as const,
      appearance: "technology" as const,
      icon: { src: icon, alt: title },
      order: 7 + index,
      x: architectureX(x),
      y: architectureY(y),
      width: 9,
      markdown: `**${title}**`,
    })),
    {
      id: "source-description",
      kind: "note",
      appearance: "transparent",
      order: 19,
      x: architectureX(4),
      y: architectureY(45),
      width: 22,
      markdown:
        "**기술 정보는 한곳에 모여 있지 않습니다.**\n\nToday in Tech는 **OpenAI, Anthropic, Google, GitHub, Hacker News** 등 다양한 공식 기술 채널의 **RSS/Atom Feed와 Sitemap**을 수집 대상으로 사용합니다. 여러 서비스에 흩어진 최신 기술 콘텐츠를 하나의 수집 파이프라인으로 통합하여 지속적으로 새로운 정보를 가져올 수 있도록 구성했습니다.",
    },
    {
      id: "pipeline-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/application.svg", alt: "Editorial Pipeline" },
      excludeFromSequence: true,
      x: architectureX(32),
      y: architectureY(7),
      width: 29,
      height: 620,
      markdown: "## Editorial Pipeline",
    },
    {
      id: "pipeline-description",
      kind: "note",
      appearance: "transparent",
      order: 19,
      x: architectureX(36),
      y: architectureY(53),
      width: 22,
      markdown:
        "**좋은 기술 아카이브는 좋은 데이터 파이프라인에서 시작됩니다.**\n\n수집한 콘텐츠는 중복 제거와 전처리를 거친 뒤, 원문을 구조화하여 AI가 활용하기 적합한 **Evidence**를 생성합니다. 생성된 Evidence를 기반으로 AI가 Markdown 문서를 작성하며, 모든 처리 과정은 **JSON Store**에 Trace 형태로 저장되어 문서가 생성되는 전체 과정을 추적하고 검증할 수 있도록 구성했습니다.",
    },
    {
      id: "collector",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/sections/backend.svg", alt: "Collector" },
      order: 12,
      x: architectureX(34),
      y: architectureY(17),
      width: 10,
      markdown: "**Collector**\n\nRSS / Sitemap",
    },
    {
      id: "preprocess",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/database.svg", alt: "Preprocess" },
      order: 13,
      x: architectureX(48),
      y: architectureY(17),
      width: 10,
      markdown: "**Preprocess**\n\nDeduplicate",
    },
    {
      id: "evidence",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/database.svg", alt: "Evidence" },
      order: 14,
      x: architectureX(34),
      y: architectureY(31),
      width: 10,
      markdown: "**Evidence**\n\nStructured Input",
    },
    {
      id: "openai-agent",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/openai.svg", alt: "OpenAI Agent" },
      order: 15,
      x: architectureX(40),
      y: architectureY(40),
      width: 10,
      markdown: "**OpenAI Agent**\n\nEditor / Writer",
    },
    {
      id: "storage",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/database.svg", alt: "JSON files" },
      order: 16,
      x: architectureX(45),
      y: architectureY(31),
      width: 14,
      markdown: "**JSON Store**\n\nraw / processed / trace",
    },
    {
      id: "archive-section",
      kind: "note",
      appearance: "section",
      icon: { src: "/icons/sections/deploy.svg", alt: "Archive and Deploy" },
      excludeFromSequence: true,
      x: architectureX(63),
      y: architectureY(7),
      width: 21,
      height: 620,
      markdown: "## Archive & Deploy",
    },
    {
      id: "archive-description",
      kind: "note",
      appearance: "transparent",
      order: 19,
      x: architectureX(63),
      y: architectureY(53),
      width: 22,
      markdown:
        "**생성된 문서는 지속적으로 축적되어 하나의 Knowledge Archive가 됩니다.**\n\nAI가 생성한 Markdown 문서는 **Docusaurus* 기반 문서 사이트에 자동으로 반영되며, **GitHub Actions**를 통해 빌드와 배포가 자동으로 수행됩니다. 이를 통해 최신 기술 콘텐츠를 지속적으로 축적하고 검색할 수 있는 기술 아카이브를 운영할 수 있도록 구성했습니다.",
    },
    {
      id: "docusaurus",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/docusaurus.svg", alt: "Docusaurus" },
      order: 17,
      x: architectureX(67),
      y: architectureY(17),
      width: 12,
      markdown: "**Docusaurus**\n\nMarkdown Archive",
    },
    {
      id: "github-actions",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/github-actions.svg", alt: "GitHub Actions" },
      order: 18,
      x: architectureX(67),
      y: architectureY(31),
      width: 12,
      markdown: "**GitHub Actions**\n\nBuild / Deploy",
    },
    {
      id: "website",
      kind: "note",
      appearance: "technology",
      icon: { src: "/icons/tech/github.svg", alt: "GitHub Pages" },
      order: 19,
      x: architectureX(67),
      y: architectureY(43),
      width: 12,
      markdown: "**GitHub Pages**\n\nPublished Archive",
    },
    {
      id: "features-title",
      kind: "note",
      appearance: "transparent",
      order: 20,
      x: featuresX(0),
      y: featuresY(0),
      width: 30,
      markdown: "# Features",
    },
    {
      id: "feature-main-page-image",
      kind: "note",
      appearance: "transparent",
      order: 21,
      x: featuresX(0),
      y: featuresY(5),
      width: 40,
      image: {
        src: "/images/today-in-tech-features/main-page.png",
        alt: "Today in Tech archive main page",
        width: 2978,
        height: 1636,
        frame: "outline",
        frameHeight: 400,
        fit: "contain",
      },
      markdown: "",
    },
    {
      id: "feature-main-page",
      kind: "note",
      appearance: "feature",
      order: 22,
      x: featuresX(0),
      y: featuresY(36),
      width: 40,
      markdown:
        "## Multi-source Collection\n\n**RSS/Atom Feed와 공식 Sitemap**을 기반으로 OpenAI, Anthropic, Google, GitHub, Hacker News 등 다양한 공식 기술 채널에서 최신 콘텐츠를 자동으로 수집합니다.",
    },
    {
      id: "feature-recommended-posts-image",
      kind: "note",
      appearance: "transparent",
      order: 23,
      x: featuresX(42),
      y: featuresY(5),
      width: 40,
      image: {
        src: "/images/today-in-tech-features/recommended-posts.png",
        alt: "Today in Tech recommended posts grid",
        width: 1816,
        height: 1188,
        frame: "outline",
        frameHeight: 400,
        fit: "contain",
      },
      markdown: "",
    },
    {
      id: "feature-recommended-posts",
      kind: "note",
      appearance: "feature",
      order: 24,
      x: featuresX(42),
      y: featuresY(36),
      width: 40,
      markdown:
        "## Intelligent Editorial Pipeline\n\n수집한 콘텐츠를 중복 제거와 후보 전처리를 거친 뒤, **AI News Editor Agent**가 기술적으로 의미 있는 글만 선별하여 문서 생성 대상으로 선택합니다.",
    },
    {
      id: "feature-trace-dashboard-image",
      kind: "note",
      appearance: "transparent",
      order: 25,
      x: featuresX(0),
      y: featuresY(48),
      width: 40,
      image: {
        src: "/images/today-in-tech-features/trace-dashboard.png",
        alt: "Today in Tech trace dashboard",
        width: 2994,
        height: 1632,
        frame: "outline",
        frameHeight: 400,
        fit: "contain",
      },
      markdown: "",
    },
    {
      id: "feature-trace-dashboard",
      kind: "note",
      appearance: "feature",
      order: 26,
      x: featuresX(0),
      y: featuresY(79),
      width: 40,
      markdown:
        "## Knowledge Traceability\n\n수집, 전처리, 원문 분석, 문서 생성까지의 전체 과정을 **Trace 형태로 저장**하여 지식이 생성되는 과정을 추적하고 검증할 수 있습니다.",
    },
    {
      id: "feature-github-actions-image",
      kind: "note",
      appearance: "transparent",
      order: 27,
      x: featuresX(42),
      y: featuresY(48),
      width: 40,
      image: {
        src: "/images/today-in-tech-features/github-actions.png",
        alt: "Today in Tech GitHub Actions workflow runs",
        width: 2986,
        height: 1412,
        frame: "outline",
        frameHeight: 400,
        fit: "contain",
      },
      markdown: "",
    },
    {
      id: "feature-github-actions",
      kind: "note",
      appearance: "feature",
      order: 28,
      x: featuresX(42),
      y: featuresY(79),
      width: 40,
      markdown:
        "## Automated Pipeline\n\n**GitHub Actions**를 통해 콘텐츠 수집, 전처리, 문서 생성, 빌드, 배포까지 전체 워크플로우를 자동화하여 지속적으로 최신 기술 아카이브를 유지합니다.",
    },
    {
      id: "results",
      kind: "note",
      appearance: "transparent",
      order: 29,
      x: outcomeX(0),
      y: outcomeY(0),
      width: 40,
      markdown:
        "# Results\n\n**기술 콘텐츠를 지속적으로 축적하는 Knowledge Archive를 만들었습니다.**\n\nToday in Tech는 콘텐츠 수집부터 전처리, Evidence 생성, AI 기반 문서 작성, Docusaurus 배포까지 이어지는 전체 큐레이션 파이프라인을 하나의 자동화된 워크플로우로 구현한 프로젝트입니다.\n\n저는 서비스별 콘텐츠 수집, Raw Snapshot 저장, 후보 전처리, Evidence 생성, AI Writer 기반 문서 작성, 운영 Trace 관리, GitHub Pages 자동 배포까지 하나의 흐름으로 연결했습니다. 이를 통해 최신 기술 정보를 단순히 소비하는 것이 아니라 지속적으로 축적하고 검색할 수 있는 기술 아카이브를 구축했습니다.",
    },
    {
      id: "lessons",
      kind: "note",
      appearance: "transparent",
      order: 30,
      x: outcomeX(44),
      y: outcomeY(4),
      width: 40,
      markdown:
        "# Lessons Learned\n\n**좋은 AI 큐레이션은 좋은 모델보다 좋은 데이터 흐름에서 시작되었습니다.**\n\nToday in Tech를 개발하면서 AI가 높은 품질의 결과를 생성하기 위해서는 모델 자체보다 어떤 데이터를 수집하고, 어떤 근거를 제공하며, 어떻게 추적 가능한 형태로 관리하는지가 더 중요하다는 점을 경험했습니다.\n\nCollector Strategy, 중복 제거, Evidence 기반 Enrichment, AI Writer 입력 설계, 운영 Trace 관리까지 하나의 파이프라인으로 설계하면서 AI 기반 콘텐츠 서비스를 안정적으로 운영하기 위한 데이터 처리와 자동화 구조를 체계적으로 정리할 수 있었습니다.",
    },
  ];

  return {
    nodes,
    edges: [
      {
        id: "sources-to-collector",
        from: { nodeId: "sources-section", side: "right" },
        to: { nodeId: "collector", side: "left" },
        directed: true,
      },
      {
        id: "collector-to-preprocess",
        from: { nodeId: "collector", side: "right" },
        to: { nodeId: "preprocess", side: "left" },
        directed: true,
      },
      {
        id: "preprocess-to-evidence",
        from: { nodeId: "preprocess", side: "bottom" },
        to: { nodeId: "evidence", side: "top" },
        directed: true,
      },
      {
        id: "evidence-to-openai-agent",
        from: { nodeId: "evidence", side: "bottom" },
        to: { nodeId: "openai-agent", side: "left" },
        directed: true,
      },
      {
        id: "openai-agent-to-docusaurus",
        from: { nodeId: "openai-agent", side: "right" },
        to: { nodeId: "docusaurus", side: "left" },
        directed: true,
      },
      {
        id: "docusaurus-to-actions",
        from: { nodeId: "docusaurus", side: "bottom" },
        to: { nodeId: "github-actions", side: "top" },
        directed: true,
      },
      {
        id: "actions-to-website",
        from: { nodeId: "github-actions", side: "bottom" },
        to: { nodeId: "website", side: "top" },
        directed: true,
      },
      {
        id: "preprocess-to-storage",
        from: { nodeId: "preprocess", side: "bottom" },
        to: { nodeId: "storage", side: "top" },
        directed: true,
      },
    ],
  };
}
